export const TAB_BAR_OPTIONS = {
  headerShown: false,
  tabBarLabelPosition: 'below-icon' as const,
  tabBarShowLabel: true,
  tabBarActiveTintColor: '#ffffff',
  tabBarInactiveTintColor: 'rgba(255, 255, 255, 0.6)',
  tabBarStyle: {
    position: 'absolute' as const,
    left: 80,
    right: 80,
    bottom: 34,
    backgroundColor: '#2563eb',
    borderTopWidth: 0,
    borderRadius: 50,
    height: 62,
    paddingBottom: 6,
    paddingTop: 6,
    paddingHorizontal: 6,
    elevation: 6,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
  },
  tabBarItemStyle: {
    flex: 1,
    marginHorizontal: 0,
    marginVertical: 0,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  tabBarIconStyle: {
    marginTop: 1,
  },
  tabBarLabelStyle: {
    fontSize: 9,
    fontWeight: '600' as const,
    marginTop: 1,
  },
};
